# Generated by Django 3.0.4 on 2020-05-24 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retweets', '0003_retweet_content'),
        ('tweets', '0001_initial'),
        ('savedTweets', '0002_auto_20200523_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtweet',
            name='retweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retweets.Retweet'),
        ),
        migrations.AlterField(
            model_name='savedtweet',
            name='tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.Tweet'),
        ),
    ]
