# Generated by Django 3.0.4 on 2020-05-23 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
        ('listUsers', '0001_initial'),
        ('users', '0002_auto_20200522_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='listuser',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.List'),
        ),
        migrations.AddField(
            model_name='listuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
