# Generated by Django 3.0.4 on 2020-05-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retweets', '0003_retweet_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retweet',
            name='originalUser',
        ),
    ]
